apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: assets.katalog.m4d.ibm.com
spec:
  group: katalog.m4d.ibm.com
  names:
    kind: Asset
    listKind: AssetList
    plural: assets
    singular: asset
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              assetDetails:
                description: Asset details
                properties:
                  connection:
                    description: Connection information
                    properties:
                      db2:
                        properties:
                          database:
                            type: string
                          port:
                            type: string
                          ssl:
                            type: string
                          table:
                            type: string
                          url:
                            type: string
                        type: object
                      kafka:
                        properties:
                          bootstrap_servers:
                            type: string
                          key_deserializer:
                            type: string
                          sasl_mechanism:
                            type: string
                          schema_registry:
                            type: string
                          security_protocol:
                            type: string
                          ssl_truststore:
                            type: string
                          ssl_truststore_password:
                            type: string
                          topic_name:
                            type: string
                          value_deserializer:
                            type: string
                        type: object
                      s3:
                        description: Connection information for S3 compatible object
                          store
                        properties:
                          bucket:
                            type: string
                          endpoint:
                            type: string
                          objectKey:
                            type: string
                          region:
                            type: string
                        required:
                        - bucket
                        - endpoint
                        - objectKey
                        type: object
                      type:
                        enum:
                        - s3
                        - db2
                        - kafka
                        type: string
                    required:
                    - type
                    type: object
                  dataFormat:
                    type: string
                required:
                - connection
                type: object
              assetMetadata:
                properties:
                  componentsMetadata:
                    additionalProperties:
                      properties:
                        componentType:
                          type: string
                        namedMetadata:
                          additionalProperties:
                            type: string
                          description: 'Named terms, that exist in Catalog toxonomy
                            and the values for these terms for columns we will have
                            "SchemaDetails" key, that will include technical schema
                            details for this column TODO: Consider create special
                            field for schema outside of metadata'
                          type: object
                        tags:
                          description: Tags - can be any free text added to a component
                            (no taxonomy)
                          items:
                            type: string
                          type: array
                      type: object
                    description: metadata for each component in asset (e.g., column)
                    type: object
                  geography:
                    type: string
                  namedMetadata:
                    additionalProperties:
                      type: string
                    type: object
                  owner:
                    type: string
                  tags:
                    description: Tags associated with the asset
                    items:
                      type: string
                    type: array
                type: object
              secretRef:
                description: Reference to a Secret resource holding credentials for
                  this asset
                properties:
                  name:
                    description: Name of the Secret resource (must exist in the same
                      namespace)
                    type: string
                required:
                - name
                type: object
            required:
            - secretRef
            - assetMetadata
            - assetDetails
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: ''
    plural: ''
  conditions: null
  storedVersions: []
