{{- if include "m4d.isEnabled" (tuple .Values.manager.enabled .Values.coordinator.enabled) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: vault-credentials
data:
  {{ if .Values.coordinator.vault.login.token }}
  VAULT_TOKEN: {{ .Values.coordinator.vault.login.token | b64enc }}
  {{ end }}
{{- end }}