apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: m4d-system/serving-cert
  creationTimestamp: null
  name: m4d-system-mutating-webhook
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: m4d-system
      path: /mutate-motion-m4d-ibm-com-v1alpha1-batchtransfer
  failurePolicy: Fail
  name: mbatchtransfer.kb.io
  rules:
  - apiGroups:
    - motion.m4d.ibm.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - batchtransfers
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: m4d-system
      path: /mutate-motion-m4d-ibm-com-v1alpha1-streamtransfer
  failurePolicy: Fail
  name: mstreamtransfer.kb.io
  rules:
  - apiGroups:
    - motion.m4d.ibm.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - streamtransfers
