# Source: m4d/templates/m4d-blueprints-ns.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: m4d-blueprints
---
# Source: m4d/templates/katalog-connector/katalog-rbac.yaml
# ClusterRole katalog-editor allows managing assets.
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: katalog-editor
rules:
  - apiGroups: ["katalog.m4d.ibm.com"]
    resources: ["assets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
---
# Source: m4d/templates/katalog-connector/katalog-rbac.yaml
# ClusterRole katalog-viewer allows viewing assets.
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: katalog-viewer
rules:
  - apiGroups: ["katalog.m4d.ibm.com"]
    resources: ["assets"]
    verbs: ["get", "list", "watch"]
---
# Source: m4d/templates/manager-auth-proxy-cr.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: m4d-proxy-cr
rules:
  - apiGroups: ["authentication.k8s.io"]
    resources:
      - tokenreviews
    verbs: ["create"]
  - apiGroups: ["authorization.k8s.io"]
    resources:
      - subjectaccessreviews
    verbs: ["create"]
---
# Source: m4d/templates/manager-cr.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: m4d-manager-cr
rules:
  - apiGroups:
      - ""
    resources:
      - events
      - secrets
      - secrets/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
      - persistentvolumeclaims/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - app.m4d.ibm.com
    resources:
      - blueprints
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - app.m4d.ibm.com
    resources:
      - blueprints/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - app.m4d.ibm.com
    resources:
      - m4dapplications
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - app.m4d.ibm.com
    resources:
      - m4dapplications/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - app.m4d.ibm.com
    resources:
      - m4dmodules
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - app.m4d.ibm.com
    resources:
      - m4dstorageaccounts
    verbs:
      - get
      - list
      - update
      - watch
  - apiGroups:
      - app.m4d.ibm.com
    resources:
      - plotters
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - app.m4d.ibm.com
    resources:
      - plotters/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - apps
    resources:
      - deployments
      - deployments/finalizers
      - deployments/status
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
      - jobs/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs/status
    verbs:
      - get
  - apiGroups:
      - com.ie.ibm.hpsys
    resources:
      - datasets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - motion.m4d.ibm.com
    resources:
      - batchtransfers
      - batchtransfers/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - motion.m4d.ibm.com
    resources:
      - batchtransfers/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - motion.m4d.ibm.com
    resources:
      - streamtransfers
      - streamtransfers/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - motion.m4d.ibm.com
    resources:
      - streamtransfers/status
    verbs:
      - get
      - patch
      - update
---
# Source: m4d/templates/katalog-connector/katalog-connector-rbac.yaml
# Grant katalog-connector the katalog-editor Role.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: katalog-connector-editor
roleRef:
  kind: ClusterRole
  name: katalog-editor
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: katalog-connector
    namespace: m4d-system
---
# Source: m4d/templates/manager-auth-proxy-crb.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: m4d-proxy-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: m4d-proxy-cr
subjects:
  - kind: ServiceAccount
    name: manager
    namespace: m4d-system
---
# Source: m4d/templates/manager-crb.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: m4d-manager-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: m4d-manager-cr
subjects:
  - kind: ServiceAccount
    name: manager
    namespace: m4d-system
---
# Source: m4d/templates/webhook-configs.yaml
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: 'm4d-system-mutating-webhook'
  annotations:
    cert-manager.io/inject-ca-from: 'm4d-system/serving-cert'
webhooks:
  - clientConfig:
      caBundle: Cg==
      service:
        name: webhook-service
        namespace: 'm4d-system'
        path: /mutate-motion-m4d-ibm-com-v1alpha1-batchtransfer
    failurePolicy: Fail
    name: mbatchtransfer.kb.io
    rules:
      - apiGroups:
          - motion.m4d.ibm.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - batchtransfers
  - clientConfig:
      caBundle: Cg==
      service:
        name: webhook-service
        namespace: 'm4d-system'
        path: /mutate-motion-m4d-ibm-com-v1alpha1-streamtransfer
    failurePolicy: Fail
    name: mstreamtransfer.kb.io
    rules:
      - apiGroups:
          - motion.m4d.ibm.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - streamtransfers
---
# Source: m4d/templates/webhook-configs.yaml
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: 'm4d-system-validating-webhook'
  annotations:
    cert-manager.io/inject-ca-from: 'm4d-system/serving-cert'
webhooks:
  - clientConfig:
      caBundle: Cg==
      service:
        name: webhook-service
        namespace: 'm4d-system'
        path: /validate-motion-m4d-ibm-com-v1alpha1-batchtransfer
    failurePolicy: Fail
    name: vbatchtransfer.kb.io
    rules:
      - apiGroups:
          - motion.m4d.ibm.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - batchtransfers
  - clientConfig:
      caBundle: Cg==
      service:
        name: webhook-service
        namespace: 'm4d-system'
        path: /validate-motion-m4d-ibm-com-v1alpha1-streamtransfer
    failurePolicy: Fail
    name: vstreamtransfer.kb.io
    rules:
      - apiGroups:
          - motion.m4d.ibm.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - streamtransfers
