name: Custom Build

on:
  workflow_dispatch:
    inputs:
      dockerTag:
        description: 'Docker Tag'
        required: true
        default: 'latest'

env:
  GO_VERSION: 1.13
  JAVA_VERSION: 11

jobs:
  build-and-publish:
    if: github.repository != 'IBM/the-mesh-for-data'
    name: Build and publish images
    runs-on: ubuntu-latest
    env:
      DOCKER_HOSTNAME: "ghcr.io"
      DOCKER_NAMESPACE: ${{ github.actor }}
      DOCKER_TAG: ${{ github.event.inputs.dockerTag }}
      DOCKER_USERNAME: ${{ github.actor }}
      DOCKER_PASSWORD: ${{ github.token }}
    steps:
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
    - uses: actions/checkout@v2
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
          ~/go/pkg/mod
          ${{ github.workspace }}/hack/tools/bin
        key: ${{ runner.os }}-custom-m2-${{ hashFiles('**/pom.xml') }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-custom
    - run: echo "Pushing images to ${DOCKER_HOSTNAME}/${DOCKER_NAMESPACE} from branch ${{ github.ref }}"
    - name: Build and push docker images
      run: make docker
    - name: Push helm charts
      run: make -C modules helm-chart-push